DocWorks for js-wixcode-sdk - no significant changes detected, but 12 issue detected
issues:
Property items is missing a type annotation (Accordion.js (40))
Property items is defined two or more times (Accordion.js (40, 56))
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (97))
Property data has an unknown type * (HtmlComponentMessageEvent.js (16))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window.js (229))
Operation get has an unknown return type * (window.js (263))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))
ERROR: Unable to parse a tag's type expression for source file /Users/simonbr/Documents/git_repos/velo-docs/wix-elements/js-wixcode-sdk/velo-docs/api/Accordion.js with tag title "type" and text "{[{Object}]}": Invalid type expression "[{Object}]": Expected "!", "$", "'", "(", "*", ".", "...", "0", "?", "@", "Function", "\"", "\\", "_", "break", "case", "catch", "class", "const", "continue", "debugger", "default", "delete", "do", "else", "enum", "export", "extends", "false", "finally", "for", "function", "if", "implements", "import", "in", "instanceof", "interface", "let", "new", "null", "package", "private", "protected", "public", "return", "static", "super", "switch", "this", "throw", "true", "try", "typeof", "undefined", "var", "void", "while", "with", "yield", "{", Unicode letter number, Unicode lowercase letter, Unicode modifier letter, Unicode other letter, Unicode titlecase letter, Unicode uppercase letter, or [1-9] but "[" found.