DocWorks for js-wixcode-sdk - 2 changes detected, but 18 issue detected changes: Service wix-window-frontend operation postMessage has changed description Service $w.LottieFake is new
issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (97))
Property data has an unknown type * (HtmlComponentMessageEvent.js (16))
Message MenuItem is defined two or more times (Lottie-fake.js (101), Menu.js (35))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window-frontend.js (201))
Operation get has an unknown return type * (window-frontend.js (234))
Operation set has an unknown param type * (window.js (235))
Operation get has an unknown return type * (window.js (269))
Callback ViewChangeOperation is defined two or more times (AppointmentField.js (347), DatePicker.js (471))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Callback ViewChangeEventHandler is defined two or more times (AppointmentField.js (362), DatePicker.js (465))
Callback Validator has an unknown param type * (ValidatableMixin.js (143))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db

Why you should do it regularly:
https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/Lottie-fake_get.es6' not found. File: Lottie-fake.js line: 36
ERROR: The @snippet tag - file 'velo-docs/examples/Lottie-fake_set.es6' not found. File: Lottie-fake.js line: 36