DocWorks for ecom-payment-settings - 8 changes detected, but 12 issue detected changes: Service ecom-payment-settings has changed description Service ecom-payment-settings operation getConfig has changed return type Service ecom-payment-settings operation getPaymentSettings has changed return type Service ecom-payment-settings operation getPaymentSettings has changed description Service ecom-payment-settings message PaymentSettingsResponse member fallbackValueForRequires3dSecure was removed Service ecom-payment-settings message PaymentSettingsResponse has a new member requires3dSecure Service ecom-payment-settings has a new message PaymentSettingsConfigResponse Service ecom-payment-settings has a new message Options
issues:
Operation getPaymentSettings has an unknown param type payment-settings.Options (payment-settings-spi.js (38))
Message Options has an unknown property type ecom-payment-settings.Order (payment-settings-spi.js (62))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: The @snippet tag - file 'velo-docs/examples/Stores-backend-Orders-createOrderFull.es6' not found. File: payment-settings-spi.js line: 423
ERROR: The @snippet tag - file 'velo-docs/examples/Stores-backend-Orders-createOrderFull.es6' not found. File: payment-settings-spi.js line: 439
ERROR: The @snippet tag - file 'velo-docs/examples/Stores-backend-Orders-createOrderFull.es6' not found. File: payment-settings-spi.js line: 451
ERROR: The @snippet tag - file 'velo-docs/examples/Stores-backend-Orders-createOrderFull.es6' not found. File: payment-settings-spi.js line: 460
ERROR: The @snippet tag - file 'velo-docs/examples/Stores-backend-Orders-createOrderFull.es6' not found. File: payment-settings-spi.js line: 469
ERROR: The @snippet tag - file 'velo-docs/examples/Stores-backend-Orders-createOrderFull.es6' not found. File: payment-settings-spi.j ...