DocWorks for payment-provider - 4 changes detected, but 6 issue detected changes: Service payment-provider message PaymentMethods member undefined was removed Service payment-provider message PaymentMethods has a new member billingAddressMandatoryFields Service payment-provider message PaymentProviderConfigResponse member undefined was removed Service payment-provider message PaymentProviderConfigResponse has a new member credentialsFields
issues:
Message ConnectAccountOptions has an unknown property type object (payment-provider-spi.js (166))
Message ConnectAccountResponse has an unknown property type object (payment-provider-spi.js (177))
Message CreateTransactionOptions has an unknown property type object (payment-provider-spi.js (218))
Message RefundOptions has an unknown property type object (payment-provider-spi.js (347))
Browserslist: caniuse-lite is outdated. Please run:
  npx browserslist@latest --update-db
  Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
ERROR: Unable to parse a tag's type expression for source file /Users/ari.gold/repos/developer-docs/jsdoc-docs/payment-provider-spi/velo-docs/api/payment-provider-spi.js with tag title "property" and text "{payment-provider~DropdownOptions []} options Options to display in the dropdown field. Each option is a key-value pair.": Invalid type expression "payment-provider~DropdownOptions []": Expected "|" but "[" found.