idanl-docbug-data-field-id-change note formatting
* DocWorks for wixcode-crm - 1 change detected
changes:
Service wix-crm.Contacts message ExtendedField member key has changed doc

* DocWorks for wix-crm-backend - 6 changes detected, but 3 issue detected
changes:
Service wix-crm-backend.Contacts operation deleteExtendedField has changed param key doc
Service wix-crm-backend.Contacts operation getExtendedField has changed param key doc
Service wix-crm-backend.Contacts operation renameExtendedField has changed param key doc
Service wix-crm-backend.Contacts message ContactInfo member extendedFields has changed doc
Service wix-crm-backend.Contacts message ExtendedField member key has changed doc
Service wix-crm-backend.Contacts message Info member extendedFields has changed doc

issues:
Operation eq has an unknown param type * (queryContacts.js (51))
Operation ne has an unknown param type * (queryContacts.js (95))
ERROR: The @snippet tag - file 'velo-docs/examples/Users-backend-register_email.es6' not found. File: emailMember.js line: 1

* DocWorks for wix-crm-frontend - 2 changes detected
changes:
Service wix-crm-frontend.Contacts message ExtendedField member key has changed doc
Service wix-crm-frontend.TriggeredEmails has changed summary

* DocWorks for dbsm-viewer-app - 4 changes detected, but 3 issue detected
changes:
Service wix-dataset.Dataset operation getCurrentItem has changed description
Service wix-dataset.Dataset operation setFieldValue has changed param fieldKey doc
Service wix-dataset.Dataset operation setFieldValues has changed param fieldValues doc
Service wix-dataset.Dataset message GetItemsResult member items has changed doc

issues:
Operation setFieldValue has an unknown param type * (datasetApi.js (390))
Operation setSort has an unknown param type wix-data.WixDataSort (datasetApi.js (939))
Operation setFilter has an unknown param type wix-data.WixDataFilter (datasetApi.js (998))

* DocWorks for js-wixcode-sdk - 3 changes detected, but 14 issue detected
changes:
Service $w.Table property rows.examples[5] has changed body
Service $w.Table message Column member dataPath has changed doc
Service $w.Table message Column member linkPath has changed doc

issues:
Message ViewChangeEventOptions has an unknown property type * (ApppointmentFieldEvent.js (8))
Operation postMessage has an unknown param type * (HtmlComponent.js (97))
Property data has an unknown type * (HtmlComponentMessageEvent.js (16))
Property fileLimit has mismatching types for get (number) and set (string) (UploadButton.js (128, 149))
Operation set has an unknown param type * (window-frontend.js (201))
Operation get has an unknown return type * (window-frontend.js (234))
Operation set has an unknown param type * (window.js (235))
Operation get has an unknown return type * (window.js (269))
Callback ViewChangeOperation is defined two or more times (AppointmentField.js (347), DatePicker.js (471))
Callback ViewChangeOperation has an unknown return type * (AppointmentField.js (347))
Callback ViewChangeEventHandler is defined two or more times (AppointmentField.js (362), DatePicker.js (465))
Callback Validator has an unknown param type * (ValidatableMixin.js (143))
Property value has an unknown type * (ValueMixin.js (62))
Property value has an unknown type * (ValueMixin.js (89))

* DocWorks for wix-members - 2 changes detected, but 2 issue detected
changes:
Service wix-members.CurrentMember message ContactDetails member customFields has changed doc
Service wix-members has changed description

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (164))
Message ContactDetails has an unknown property type object (members_shared.js (18))

* DocWorks for wix-members-backend - 3 changes detected, but 1 issue detected
changes:
Service wix-members-backend.Members message ContactDetails member customFields has changed doc
Service wix-members-backend.Members message ContactInfo member customFields has changed doc
Service wix-members-backend has changed description

issues:
Message ContactDetails has an unknown property type object (members_shared.js (18))

* DocWorks for wix-members-frontend - 2 changes detected, but 2 issue detected
changes:
Service wix-members-frontend.CurrentMember message ContactDetails member customFields has changed doc
Service wix-members-frontend has changed description

issues:
Message FieldsetOptions is defined two or more times (getMember.js (1), members_shared.js (162))
Message ContactDetails has an unknown property type object (members_shared.js (18))

* DocWorks for wix-crm-frontend - 1 change detected
changes:
Service wix-crm-frontend.TriggeredEmails has changed description

* DocWorks for wix-crm-frontend - 1 change detected
changes:
Service wix-crm-frontend.TriggeredEmails has changed description

---------

Co-authored-by: idanlib-wix <idanli@wix.com>